[package]
name = "breezebuddy"
version = "0.0.1"
authors = ["David Fölk david@foelk.com"]
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = "0.8.2"
sysinfo = "0.30.11"
