name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install requirements
        run: |
          sudo apt-get install -y libpango1.0-dev
          export PKG_CONFIG_PATH="/usr/lib/pkgconfig"
      - name: Build
        run: |
          cd breezebuddy
          cargo build --verbose
      - name: Run tests
        run: |
          cd breezebuddy
          cargo test --verbose

